eldpswp99 assignment
wafflestudio/rookies pull request #276
Opened 2020-11-11 09:09 UTC by eldpswp99

2020-11-11 11:39 UTC, gyusang commented
24줄이 추가되었는데, 일부러 엔터를 추가하신 건가요?

2020-11-11 12:00 UTC, eldpswp99 commented
엥 다시 체크해보겠습니다

2020-11-11 12:01 UTC, eldpswp99 commented
formatter 때문이네요 다시 커밋하도록 하겠습니다 확인 감사합니다!

2020-11-11 13:18 UTC, davin111 approved these changes

2020-11-11 13:19 UTC, davin111 requested changes
`.Rhistory`라는 파일 삭제 해주세요!

2020-11-11 15:54 UTC, eldpswp99 commented
??? 저건 또 무슨파일이지.. 삭제하고 다시 커밋하겠습니다

2020-11-11 16:52 UTC, YeonghyeonKO commented
@eldpswp99 Rhistory 파일은 주로 R 돌리고 나면 나오는 로그 같은 건데 혹시 R도 쓰시나요?

2020-11-12 01:20 UTC, eldpswp99 commented
> @eldpswp99 Rhistory 파일은 주로 R 돌리고 나면 나오는 로그 같은 건데 혹시 R도 쓰시나요?

RStudio를 깔았더니 마크다운 파일을 R studio로 열던데 그거때문이었나보네요 수정후 커밋하겠습니다

2020-11-12 01:30 UTC, closed without merging