Delete duplicate
wafflestudio/rookies pull request #340
Opened 2020-11-23 05:11 UTC by pullup-dip-burpee

2020-11-23 12:24 UTC, gyusang requested changes
https://github.com/pullup-dip-burpee/rookies/blob/91a035b5f6d636d2d15bbde07c88a2e3a6bd325c/backend/seminar4/assignment-servers.md#L84-L90
부분 삭제 부탁드립니다.
자동 Merge에 문제가 있어 보입니다.

2020-11-23 12:27 UTC, gyusang commented on backend/seminar4/assignment-servers.md
84~90 줄입니다!

2020-11-23 14:32 UTC, pullup-dip-burpee commented
> https://github.com/pullup-dip-burpee/rookies/blob/91a035b5f6d636d2d15bbde07c88a2e3a6bd325c/backend/seminar4/assignment-servers.md#L84-L90
> 부분 삭제 부탁드립니다.
> 자동 Merge에 문제가 있어 보입니다.

아 혹시 아직 conflict 있다고 뜨시나요??

2020-11-23 14:35 UTC, gyusang commented
@pullup-dip-burpee 아니요 지금 conflict는 없는데, 84~90 줄이 의도치 않게 추가된 것 같습니다.
그 부분은 #329 에서 삭제되었습니다.

2020-11-23 20:56 UTC, davin111 commented
@pullup-dip-burpee files changed 보시고 의도하시는 게 맞는지 잘 확인해주세요.

2020-11-24 00:53 UTC, pullup-dip-burpee commented
제가 실수했네요 ㅠㅠ 수정해서 풀리퀘 올렸습니다!

2020-11-24 02:22 UTC, YeonghyeonKO commented on backend/seminar4/assignment-servers.md
>  ### 박은천([@pullup-dip-burpee](https://github.com/pullup-dip-burpee))
케틀벨 멋있군요

2020-11-25 02:22 UTC, gyusang approved these changes

2020-11-25 16:01 UTC, davin111 approved these changes
This PR will resolve #329 issue.

2020-11-25 16:02 UTC, merged